### ISSUE TITLE
Adding additional headers to the installed build

### ISSUE THREAD

**Issue by mattpitkin** [eggplantbren/RJObject#2]
Hi Brendon,

Is there any reason why the files `RJObject.h` and `RJObjectImpl.h` are not included in the `CMakeLists.txt` file to be included in the build? I think these should be added to make RJObject more useful as a library. This would also require the following changes:

In `RJObjectImpl.h` change:

``` c
#include "RandomNumberGenerator.h"
#include "Utils.h"
```

to

``` c
#include <dnest3/RandomNumberGenerator.h>
#include <dnest3/Utils.h>
```

Then, in `CMakeLists.txt` have

``` cmake
set (RJOBJ_INCLUDES
     Distributions/BasicCircular.h
     Distributions/ClassicMassInf.h
     Distributions/Distribution.h
     Distributions/Pareto.h
     RJObject.h
     RJObjectImpl.h
)
```

Cheers,

Matt

**Comment by eggplantbren** [comment]
Hi Matt,

I don't know. What would this do? .h files are never compiled directly, so
should they be included here?
- Brendon

On Thu, Aug 13, 2015 at 4:08 PM, Matt Pitkin notifications@github.com
wrote:

> Hi Brendon,
> 
> Is there any reason why the files RJObject.h and RJObjectImpl.h are not
> included in the CMakeLists.txt file to be included in the build? I think
> these should be added to make RJObject more useful as a library. This would
> also require the following changes:
> 
> In RJObjectImpl.h change:
> 
> #include "RandomNumberGenerator.h"
> #include "Utils.h"
> 
> to
> 
> #include <dnest3/RandomNumberGenerator.h>
> #include <dnest3/Utils.h>
> 
> Then, in CMakeLists.txt have
> 
> set (RJOBJ_INCLUDES
>      Distributions/BasicCircular.h
>      Distributions/ClassicMassInf.h
>      Distributions/Distribution.h
>      Distributions/Pareto.h
>      RJObject.h
>      RJObjectImpl.h
> )
> 
> Cheers,
> 
> Matt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eggplantbren/RJObject/issues/2.

## 

Dr Brendon J. Brewer
Department of Statistics, The University of Auckland, New Zealand
Ph: +64 27 500 1336
Web: http://www.stat.auckland.ac.nz/~brewer/

**Comment by mattpitkin** [comment]
Hi Brendon,

Basically this means that if you're using RJObject as a library you only need to point to the one location for including the headers. Otherwise, you'd have to point to two different locations - the one where the stuff in `Distributions` are located and the one where the `RJObject` headers are. I don't think it would do any harm having them included.

Matt

**Comment by mattpitkin** [comment]
Looking again the header inclusion in `RJObjectImpl.h`:

``` c
#include "RandomNumberGenerator.h"
#include "Utils.h"
```

should be ok just changed to

``` c
#include <RandomNumberGenerator.h>
#include <Utils.h>
```

without the `dnest3` in the path, because the cmake build already adds the proper include path for DNest3.

**Comment by eggplantbren** [comment]
Hi Matt,

If you were to make a pull request with a minimal set of changes that would
solve the problem, I'll happily accept it. I'm on vacation at the moment so
don't have much "free" ;) time to look into this.
- Brendon

On Fri, Aug 14, 2015 at 10:06 AM, Matt Pitkin notifications@github.com
wrote:

> Looking again the header inclusion in RJObjectImpl.h:
> 
> #include "RandomNumberGenerator.h"
> #include "Utils.h"
> 
> should be ok just changed to
> 
> #include <RandomNumberGenerator.h>
> #include <Utils.h>
> 
> without the dnest3 in the path, because the cmake build already adds the
> proper include path for DNest3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eggplantbren/RJObject/issues/2#issuecomment-131012875
> .

## 

Dr Brendon J. Brewer
Department of Statistics, The University of Auckland, New Zealand
Ph: +64 27 500 1336
Web: http://www.stat.auckland.ac.nz/~brewer/

**Comment by mattpitkin** [comment]
Sure, the pull request (#3) is made. Enjoy your holiday!

**Comment by mattpitkin** [comment]
Pull request #3 has been merged, so I'll close this issue
